### ISSUE TITLE
python error instead of XCE warning when user forgets to select target

### ISSUE THREAD

**Issue by tkrojer** [xchem/XChemExplorer#132]
python throws error because CheckAutoProcessing does not exist

Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 2650, in button_clicked
    self.prepare_and_run_task(instruction)
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 2698, in prepare_and_run_task
    self.check_for_new_autoprocessing_results()
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 317, in check_for_new_autoprocessing_results
    start_thread = CheckAutoProcessing().query(self)
NameError: global name 'CheckAutoProcessing' is not defined

**Comment by reskyner** [comment]
Added a line to print a warning in the terminal, indicating that a target has not been selected. A traceback error is a high-level bug.

**Comment by tkrojer** [comment]
Rachael solved the bug in February.; I've introduced a new option in v1.2 which enables parsing of the project directory in case users reprocessed files.
