### ISSUE TITLE
Deposition dropdown: Edit information (Rachael broke it - sorry)

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#32]
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 1099, in deposition_data
    'object.set_primary_citation_as_structure_authors')
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/gui_scripts/layout.py", line 355, in add_checkbox
    eval(str('checkbox.stateChanged.connect(' + function + ')'))
  File "<string>", line 1, in <module>
AttributeError: type object 'object' has no attribute 'set_primary_citation_as_structure_authors'

Obviously important - will fix this weekend

**Comment by reskyner** [comment]
Fixed. reference to function was wrong. 

Will update with push when other urgent errors are fixed.
