### ISSUE TITLE
Deposition dropdown: Check SMILES (Rachael broke another thing...)

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#33]
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/lib/XChemDeposit.py", line 1049, in run
    elementDict_smiles=smilestools(LigandSmiles).ElementDict()
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/lib/XChemUtils.py", line 2312, in ElementDict
    for atom in m.GetAtoms():
AttributeError: 'NoneType' object has no attribute 'GetAtoms

Weekend is starting to look busy

**Comment by reskyner** [comment]
False alarm. This is only an error due to my current test dataset. Is exactly the same in the old version of XCE. Will close for now, but will need to double check with Tobias if this usually works.
