### ISSUE TITLE
xce fails to load outside of dls prepared folder: proasis_project_label

### ISSUE THREAD

**Issue by nelse003** [xchem/XChemExplorer#48]
xce fails to load when loaded from folders not with prepared path. Might not be an issue in normal use.

Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 3976, in <module>
    app = XChemExplorer(sys.argv[1:])
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 66, in __init__
    self.start_GUI()
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 92, in start_GUI
    LayoutObjects(self).main_layout(self)
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/gui_scripts/layout.py", line 228, in main_layout
    menu_bar = self.initialise_menu_bar(xce_object)
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/gui_scripts/layout.py", line 45, in initialise_menu_bar
    setup().top_menu_dict(xce_object)
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/gui_scripts/settings_preferences.py", line 385, in top_menu_dict
    [str(xce_object.proasis_project_label), '', xce_object.proasis_project_function],
AttributeError: 'XChemExplorer' object has no attribute 'proasis_project_label'

**Comment by nelse003** [comment]
/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py: 

Is my path doing something stupid?

**Comment by reskyner** [comment]
where are you trying to run from?

**Comment by nelse003** [comment]
I was just running direct from a new terminal session so
/home/jot97277/desktop. For sanity: which xce:
/dls/science/groups/software/XChem/xce

**Comment by reskyner** [comment]
Should work now!

**Comment by reskyner** [comment]
This is definitely fixed.
