### ISSUE TITLE
Selecting autoproc method doesn't update datasets/summary table

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#58]
The table that shows up when you click 'show details' should update the main table when you click on an autoproc row, but it doesn't

**Comment by reskyner** [comment]
Example error from test data:

Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 3616, in user_update_selected_autoproc_datasets_summary_table
    dbTmp = self.xtal_db_dict[key]
KeyError: 'JMJD2DA-x1622'

For some reason, self.xtal_db_dict possibly isn't being updated

**Comment by reskyner** [comment]
self.xtal_db_dict is not being setected at all at this point (checked by trying to print it out). I think it's not updating when the table is updated, maybe

**Comment by reskyner** [comment]
Works if you update tables after getting new results from autoprocessing on my test dataset. Paddy is getting an error though:

/dls/labxchem/data/2017/lb18145-3/processing/Tony-Patrick/processing

('===>', 'NUDT7A-x1450', 'None')
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 3619, in user_update_selected_autoproc_datasets_summary_table
    if int(stage) > 2:
ValueError: invalid literal for int() with base 10: 'None'
('===>', 'NUDT7A-x1450', 'None')
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 3619, in user_update_selected_autoproc_datasets_summary_table
    if int(stage) > 2:
ValueError: invalid literal for int() with base 10: 'None'
('===>', 'NUDT7A-x1450', 'None')
Traceback (most recent call last):
  File "/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/XChemExplorer.py", line 3619, in user_update_selected_autoproc_datasets_summary_table
    if int(stage) > 2:
ValueError: invalid literal for int() with base 10: 'None'

stage variable is pulled from self.xtal_db_dict, which doesn't seem to be picked up unless 'update tables from datasource' button is clicked. I will add the function to run when 'get new results from autoprocessing' is done.

**Comment by reskyner** [comment]
This is fixed. Tested on paddy's problem data. Used the update table solution in previous comment
